// config.js，根目录的common文件夹中
export default {
	token: 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJiNDBlOGU3ZmY4Yzc0YThhYmNjNDQzZGE0ZGQ2M2Q5NSIsInN1YiI6IjEiLCJpc3MiOiJ6emQiLCJpYXQiOjE2NzM3MTQwMjAsImV4cCI6MTcwNDgxODAyMH0.BZoLUUe1zVUzoVslJFIMNLSiZaHxLjRiFG6mq8wN6nQ',
}